services:
  credit_risk_api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./mlruns_data:/app/mlruns
    environment:
      - MLFLOW_TRACKING_URI=file:////app/mlruns
      - MLFLOW_REGISTRY_URI=sqlite:////app/mlruns/mlruns.db # <--- THIS IS THE CRITICAL CHANGE

  model_trainer:
    build: .
    volumes:
      - ./mlruns_data:/app/mlruns
    environment:
      - MLFLOW_TRACKING_URI=file:////app/mlruns
      - MLFLOW_REGISTRY_URI=sqlite:////app/mlruns/mlruns.db # <--- AND THIS ONE
    command: python /app/src/model_training.py