name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9' # Or your preferred version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest # Ensure pytest is installed for running tests

    - name: Run tests
      run: |
        pytest tests/

    # Optional: Add linting, formatting checks (e.g., flake8, black)
    # - name: Run Flake8 linter
    #   run: |
    #     pip install flake8
    #     flake8 src/

    # Optional: Build Docker image (for later deployment)
    # - name: Build Docker image
    #   run: |
    #     docker build -t credit-risk-model-api .